"""
Give random word from word list
"""


from random import choice

word_list = ['PRODUCTIVE', 'EDUCATED', 'OFFER', 'CAGEY', 'LOCK', 'WIGGLY', 'PASS', 'UNHEALTHY', 'OSSIFIED', 'BEE', 'DIFFICULT', 'LIVE', 'SNOW', 'SAFE', 'FLAME', 'WHISPER', 'OBSOLETE', 'STEP', 'USEFUL', 'CHEAP', 'LEWD', 'SPOOKY', 'BLADE', 'SUBTRACT', 'COMMON', 'DECISIVE', 'SHOE', 'EXCITING', 'PANCAKE', 'IMPARTIAL', 'SHEEP', 'NAPPY', 'AGONIZING', 'SMALL', 'MARBLE', 'HELP', 'BREATH', 'AUTOMATIC', 'LOSS', 'KITTY', 'TRUST', 'CANNON', 'PASTE', 'VOLATILE', 'MARKET', 'DROP', 'PRICEY', 'TOP', 'BRAWNY', 'REJOICE', 'JOG', 'COWS', 'PATHETIC', 'SECRET', 'PAT', 'EMPTY', 'CRAVEN', 'BLOT', 'CLASSY', 'BLOW', 'FIVE', 'STATEMENT', 'BABY', 'DIVISION', 'BOILING', 'THUNDERING', 'PROVIDE', 'MAID', 'PRESERVE', 'ASHAMED', 'STROKE', 'CROWDED', 'PIE', 'CRASH', 'GIDDY', 'SUCCEED', 'GUARDED', 'ORGANIC', 'ZEALOUS', 'TRAMP', 'CALLOUS', 'HAPPY', 'PRACTICE', 'SUCCESSFUL', 'EDUCATE', 'BOIL', 'SUDDEN', 'CAT', 'TEAM', 'COMPARISON', 'SPIKY', 'MEN', 'TIN', 'SMOGGY', 'CROWD', 'MAILBOX', 'REQUEST', 'AHEAD', 'VIVACIOUS', 'SNAKES']

def random_word():
    return choice(word_list)


"""
Created on Tue Nov 12 01:23:33 2024
@author: csesohag02
"""
